apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeshop-frontend
  labels:
    app: kubeshop-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubeshop-frontend
  template:
    metadata:
      labels:
        app: kubeshop-frontend
    spec:
      containers:
        - name: frontend
          image: kubeshop-frontend:v6
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: kubeshop-frontend
  labels:
    app: kubeshop-frontend
spec:
  type: ClusterIP
  selector:
    app: kubeshop-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80