apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeshop-config
  namespace: kubeshop
data:
  POSTGRES_DB: "kubeshop"
  POSTGRES_USER: "kubeshop"

  PGHOST: "postgres"
  PGPORT: "5432"
  PGDATABASE: "kubeshop"
  PGUSER: "kubeshop"

  REDIS_URL: "redis://redis:6379"
  SESSION_TTL_SECONDS: "3600"